version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - html  # You can add other formats if needed, such as pdf

build:
  image: readthedocs/build:latest

# Include the 'html' directory (or any other static content directory)
static:
  - html
