# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import  # Install ghp-import to be used in deployment

      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: List files in docs/build
        run: ls -R docs/build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          if [ -d "docs/build/html" ]; then
            echo "Deploying to GitHub Pages"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://ooge0:${{ secrets.MY_GITHUB_TOKEN }}@github.com/ooge0/sphinx-demo-app.git
            ghp-import -n -p -f docs/build/html
          else
            echo "Error: docs/build/html directory not found. Skipping deployment."
            exit 1
          fi
