# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up Python 3.10 environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Installs dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs the Sphinx build process to generate HTML documentation
      - name: Build HTML
        run: |
          cd docs/
          make html

      # Lists the contents of docs/build to confirm the generated files
      - name: List files in docs/build
        run: ls -R docs/build

      # Deploys the built documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          if [ -d "docs/build/html" ]; then
            echo "Deploying to GitHub Pages"
            ghp-import -n -p -f docs/build/html
          else
            echo "Error: docs/build/html directory not found. Skipping deployment."
            exit 1
          fi
