name: Build-sphinx-docs

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import  # Install ghp-import tool

      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f docs/_build/html
