# This is a basic workflow to build and deploy Sphinx documentation

name: Build-and-Deploy-Sphinx-Docs

# Workflow triggers
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import

      # Step 4: Build the HTML documentation
      - name: Build HTML Documentation
        run: |
          cd docs/
          make html

      # Step 5: Verify the build directory
      - name: List Built Files
        run: ls -R docs/build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -d "docs/build/html" ]; then
            echo "Deploying to GitHub Pages"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            ghp-import -n -p -f docs/build/html
          else
            echo "Error: docs/build/html directory not found. Skipping deployment."
            exit 1
          fi
