name: Build-sphinx-docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import

      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: List files in docs/_build
        run: ls -R docs/_build

      - name: Deploy to GitHub Pages
        run: |
          if [ -d "docs/_build/html" ]; then
            ghp-import -n -p -f docs/_build/html
          else
            echo "Error: docs/_build/html directory not found. Skipping deployment."
            exit 1
          fi
